version: '3'
services:
  cypress:
    build: .
    # volumes:
    #   - ./cypress/results:/app/cypress/results
    command: "npm run cy:run"
    volumes:
      - ./cypress/reports/screenshots:/app/cypress/results/screenshots