version: '3'
services:
  cypress:
    image: cypress/browsers:node14.16.0-chrome89-ff86
    volumes:
      - ./:/app
    working_dir: /app

# version: '3.2'
# services:
#   cypress:
#     image: "cypress/included:3.2.0"
#     working_dir: -w /e2e/pace/front
#     volumes:
#       - ./:/e2e