version: 2.1

orbs:
  cypress: cypress-io/cypress@3
jobs:
  build-and-test:
    docker:
      - image: cypress/included:8.4.0
    steps:
      - checkout
      - run: npx cypress run
      - store_artifacts:
          path: cypress/results
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run