version: 2.1

jobs:
  build:
    docker:
      - image: my-image:latest #docker:20.10.11
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: my-image:latest
    steps:
      - checkout
      - run: npx cypress run
      - store_artifacts:
          path: cypress/results/screenshots
          destination: screenshots
      - store_artifacts:
          path: cypress/results/videos
          destination: videos
workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
