version: 2.1

orbs:
  cypress: cypress-io/cypress@3
jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run: node --version

# workflows:
#   use-my-orb:
#     jobs:
#       - cypress/run:
#           cypress-command: npx cypress run