version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:14.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start Cypress on the host machine
          background: true
          command: |
            export DISPLAY=:99
            Xvfb :99 -screen 0 1024x768x16 &
            sleep 3
            npx cypress run
      - run:
          name: Build and test
          command: |
            docker-compose build
            docker-compose run cypress
      - store_artifacts:
          path: cypress/results/screenshots
          destination: screenshots
      - store_artifacts:
          path: cypress/results/videos
          destination: videos

workflows:
  main:
    jobs:
      - build-and-test
