version: 2.1

jobs:
  build-and-test:
    docker:
      - image: docker:20.10.11
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            apt-get update
            apt-get install -y docker-compose
      - run:
          name: Build and test
          command: |
            docker-compose up
      - store_artifacts:
          path: cypress/results/screenshots
          destination: screenshots
      - store_artifacts:
          path: cypress/results/videos
          destination: videos

workflows:
  main:
    jobs:
      - build-and-test
