version: 2.1

orbs:
  cypress: cypress-io/cypress@3
jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npx cypress run
      - store_artifacts:
          path: results
          destination: results
      - store_test_results:
          path: results

# workflows:
#   use-my-orb:
#     jobs:
#       - cypress/run:
#           cypress-command: npx cypress run