version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:14.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Create screenshots directory
          command: mkdir -p /home/circleci/project/cypress/results/screenshots
      - run:
          name: Build and test
          command: |
            docker-compose build
            docker-compose run cypress
      - store_artifacts:
          path: cypress/screenshots/

workflows:
  main:
    jobs:
      - build-and-test
