version: 2.1
orbs:
  cypress: cypress-io/cypress@3
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:14.0
    steps:
      - checkout
      - run:
          name: Open Cypress UI
          command: npx cypress open
      - setup_remote_docker
      - run:
          name: Build and test
          command: |
            docker-compose build
            docker-compose run cypress
      - store_artifacts:
          path: cypress/results/screenshots
          destination: screenshots
      - store_artifacts:
          path: cypress/results/videos
          destination: videos

workflows:
  main:
    jobs:
      - build-and-test
