version: 2.1

jobs:
  build-and-test:
    docker:
      - image: docker:20.10.11
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            su -c curl -l "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            su -c chmod +x /usr/local/bin/docker-compose
      - setup_remote_docker
      - run:
          name: Build and test
          command: |
            docker-compose build
            docker-compose run cypress
      - store_artifacts:
          path: cypress/results/screenshots
          destination: screenshots
      - store_artifacts:
          path: cypress/results/videos
          destination: videos

workflows:
  main:
    jobs:
      - build-and-test
