version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:14.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and test
          command: |
            docker-compose build
            docker-compose run cypress
      # - run: |
      #       docker cp app:/output /path/in/your/job/space
workflows:
  main:
    jobs:
      - build-and-test
