version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:14.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and test
          command: |
            docker-compose build
            docker-compose run cypress
      - run:
          command: |
            mkdir -p /tmp/core_dumps
            cp core.* /tmp/core_dumps
          when: on_fail
      - store_artifacts:
          path: /tmp/core_dumps

workflows:
  main:
    jobs:
      - build-and-test
