version: 2.1

orbs:
  cypress: cypress-io/cypress@3
jobs:
  build:
    docker:
      - image: cimg/node:19.8.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - checkout
      - run: npm install
      - run: docker build -t my-cy-image .
      - run: docker run -t my-cy-image            
workflows:
  build:
    jobs:
      - build


# workflows:
#   use-my-orb:
#     jobs:
#       - cypress/run:
#           cypress-command: npx cypress run