version: 2.1

orbs:
  cypress: cypress-io/cypress@3

jobs:
  build-and-test:
    executor: cypress/default
    steps:
      - checkout
      - cypress/install
      - run:
          name: Run Cypress tests
          command: npx cypress run
    workflows:
      version: 2
      build-and-test:
        jobs:
          - build-and-test