version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:14.0
    working_directory: /tmp
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and test
          command: |
            docker-compose build
            docker-compose run cypress
      - store_artifacts:
          path: /tmp
          destination: artifact-file


workflows:
  main:
    jobs:
      - build-and-test
