version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:14.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and test
          command: |
            docker-compose build
            docker-compose run cypress
      - run: |
            docker cp app:/cypress/results/screenshots /app/cypress/results/screenshots
workflows:
  main:
    jobs:
      - build-and-test
