version: 2.1

orbs:
  cypress: cypress-io/cypress@3
jobs:
  build:
    docker:
      - image: cimg/node:19.8.1
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run Cypress
          command: >
            docker build -t my-cy-image .
            docker run -t my-cy-image            
workflows:
  build:
    jobs:
      - build
# workflows:
#   use-my-orb:
#     jobs:
#       - cypress/run:
#           cypress-command: npx cypress run