version: 2.1

orbs:
  cypress: cypress-io/cypress@
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run
          install-browsers: true
          start-command: 'npx cypress run'